language: cpp
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "VED/CgiKeSHoEieXZjzlgaOfWEhUl84b1xOSSuZnZ0DQeOTMeZ8+qewdloyRO+WaLNk7p1H9+FwgwRRzy91ljkfoXP1cb1f1LpPwivZv2Ffb2LY1twKXNb8iR8/kr+hQe1SBW1aHID0KFlEUuDu3VycWAXqKTWdjS2EY+6HAi5s="

before_install:
 - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
 - sudo apt-get update -qq
 - sudo apt-get install -qq gperf libasio-dev libboost-dev libc-ares-dev libdb++-dev libpopt-dev libssl-dev perl libmysqlclient-dev libpq-dev libfreeradius-client-dev libcppunit-dev autotools-dev libpcre3-dev libxerces-c-dev curl libcajun-dev python-cxx-dev libsipxtapi-dev libsrtp-dev
 - sudo add-apt-repository -y "deb http://http.debian.net/debian/ sid main"
 - sudo apt-get update -qq
 - sudo apt-get install -qq --force-yes libfreeradius-client-dev libcajun-dev libsipxtapi-dev

compiler:
  - gcc

script:
#  - ./build/travis/bootstrap
#  - ./build/travis/configure
#  - ./build/travis/build

addons:
  coverity_scan:

    # GitHub project metadata
    project:
      name: resiprocate/resiprocate
      description: "reSIProcate SIP stack"

    # Where email notification of build analysis results will be sent
    notification_email: gjasny@googlemail.com

    # Commands to prepare for build_command
    build_command_prepend: ./build/travis/bootstrap && ./build/travis/configure

    # The command that will be added as an argument to "cov-build" to compile your project for analysis,
    build_command: make

    # Pattern to match selecting branches that will run analysis. We recommend leaving this set to 'coverity_scan'.
    # Take care in resource usage, and consider the build frequency allowances per
    #   https://scan.coverity.com/faq#frequency
    branch_pattern: coverity_scan
